name: Coding Stats

on:
  schedule: # executes once a week
    - cron: "59 23 * * 0"
  workflow_dispatch:

jobs:
  gh-stats:
    runs-on: ubuntu-latest
    name: Github Stats
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env: # default use ${{ secrets.SUMMARY_GITHUB_TOKEN }}, you should replace with your personal access token
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          USERNAME: ${{ github.repository_owner }}
          # BRANCH_NAME is optional, default to main, branch name to push cards
          BRANCH_NAME: "main"
          # UTC_OFFSET is optional, default to zero
          UTC_OFFSET: 1 
          # EXCLUDE is an optional comma seperated list of languages to exclude, defaults to ""
          EXCLUDE: "Makefile"
          # AUTO_PUSH is optional, a boolean variable default to true, whether automatically push generated files to desired branch 
          AUTO_PUSH: true
  wakatime:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME }}
          TIME_RANGE: last_30_days
          IGNORED_LANGUAGES: Binary YAML JSON TOML Other
          SHOW_TOTAL: true
          SHOW_TITLE: true
          SHOW_TIME: true
